apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "reporting.fullname" . }}-config
  labels:
    {{- include "reporting.labels" . | nindent 4 }}
data:
  APP_MESSAGE: "{{ .Values.config.APP_MESSAGE }}"
